"use client";

import { captureException, captureMessage } from "@/lib/monitoring";

import {
  validateDraft,
  type OrderErrors,
  type OrderRequest,
} from "@/lib/order";
import type { WhatsAppHandoff } from "./whatsapp-service";
import { err, failure, ok, type Failure, type Result } from "./result";

/**
 * The service layer. The UI talks to this, and to nothing else.
 *
 * It never imports Supabase. It posts to our own route handler, which validates
 * the request a second time on the server before it touches the database —
 * because a client that can be trusted is a client that hasn't been opened in
 * devtools yet.
 *
 * Everything that can go wrong on the way is caught here and returned as a value:
 * no promise rejects into a component, ever.
 */

export type SubmittedOrder = {
  id: string;
  /** Short, speakable: TRJ-1A2B3C4D. Generated by the database. */
  reference: string;
  createdAt: string;
  status: string;
};

export type SubmittedOrderResult = {
  order: SubmittedOrder;
  /** Built on the server from the stored row. Null when no number is configured. */
  whatsapp: WhatsAppHandoff | null;
};

export type OrderFailure = Failure<OrderErrors>;

/** A request that hangs is worse than one that fails: fail it ourselves. */
const TIMEOUT_MS = 12_000;

/** Not a failure, but not healthy either. Worth knowing before it becomes one. */
const SLOW_MS = 4_000;

export async function submitOrderRequest(
  request: OrderRequest,
): Promise<Result<SubmittedOrderResult, OrderFailure>> {
  // Validate before we spend the founder's connection on a request we know is bad.
  const fields = validateDraft({
    projectName: request.projectName,
    fullName: request.fullName,
    phone: request.phone,
    notes: request.notes,
  });

  if (Object.keys(fields).length) {
    return err(
      failure<OrderErrors>(
        "validation",
        "راجع الحقول المطلوبة ثم أعد المحاولة.",
        {
          fields,
          retryable: false,
        },
      ),
    );
  }

  if (typeof navigator !== "undefined" && navigator.onLine === false) {
    return err(
      failure<OrderErrors>(
        "offline",
        "لا يوجد اتصال بالإنترنت. تحقق من الشبكة وأعد المحاولة.",
        {
          retryable: true,
        },
      ),
    );
  }

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), TIMEOUT_MS);
  const startedAt = Date.now();

  try {
    const response = await fetch("/api/orders", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(request),
      signal: controller.signal,
      cache: "no-store",
    });

    if (!response.ok) {
      const body = (await response.json().catch(() => null)) as {
        error?: OrderFailure;
      } | null;

      if (body?.error?.code) return err(body.error);

      return err(
        failure<OrderErrors>(
          "server",
          "تعذّر إرسال الطلب. حاول مرة أخرى بعد قليل.",
          {
            retryable: true,
          },
        ),
      );
    }

    const elapsed = Date.now() - startedAt;
    if (elapsed > SLOW_MS) {
      captureMessage("Slow order submission", {
        severity: "warning",
        extra: { duration_ms: elapsed, status: response.status },
      });
    }

    const body = (await response.json()) as {
      order?: SubmittedOrder;
      whatsapp?: WhatsAppHandoff | null;
    };
    if (!body.order?.id) {
      return err(
        failure<OrderErrors>(
          "server",
          "تعذّر تأكيد الطلب. حاول مرة أخرى بعد قليل.",
          {
            retryable: true,
          },
        ),
      );
    }

    return ok({ order: body.order, whatsapp: body.whatsapp ?? null });
  } catch (error) {
    if (error instanceof DOMException && error.name === "AbortError") {
      captureMessage("Order submission timed out", {
        severity: "warning",
        extra: { timeout_ms: TIMEOUT_MS },
      });

      return err(
        failure<OrderErrors>(
          "timeout",
          "استغرق الإرسال وقتًا طويلًا. حاول مرة أخرى.",
          {
            retryable: true,
          },
        ),
      );
    }

    captureException(error, {
      message: "Order submission failed to reach the server",
    });

    return err(
      failure<OrderErrors>(
        "network",
        "تعذّر الوصول إلى الخادم. تحقق من اتصالك وأعد المحاولة.",
        {
          retryable: true,
        },
      ),
    );
  } finally {
    clearTimeout(timer);
  }
}
